const routeConstants = {
    USER_HOME_PAGE: '/',
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    REGISTER: '/register',
    CART: '/cart',
    FILL_INFORMATION: '/fill-information',
    FIND_TOUR: '/find-tour',
    CUSTOM_TOUR: '/custom-tour',
    SEARCH_RESULTS: '/search-results',
    USER_PROFILE: '/user-profile',
    USER_CHANGE_PASSWORD: '/change-password',
    LOVE_LIST: '/wishlist',
    SCHEDULE_DETAIL: '/tour/schedule/detail/:tour_id',
    DETAIL_TOUR: '/tour/information/detail/:tour_id',
    PAYMENT_SUCCESS: '/payment/success',
    USER_ORDERS: '/orders',
    USER_LIST_CUSTOM_TOURS: '/user-list-custom-tours',
    MESSAGE: '/message',
    ADMIN_HOMEPAGE: '/admin',
    ADMIN_MANAGE_TOURS: '/admin/manage-tours',
    ADMIN_EDIT_TOUR: '/admin/edit-information-tour/:tour_id',
    ADMIN_MANAGE_TOUR_GUIDE: '/admin/manage-tour-guide',
    ADMIN_ASSIGN_NEW_TASK: '/admin/assign-new-task',
    ADMIN_ADD_NEW_TOUR: '/admin/add-new-tour',
    ADMIN_NOTIFICATION: '/admin/notification',
    ADMIN_MANAGE_NOTIFICATION: '/admin/manage-notification',
    ADMIN_MANAGE_TOURIST: '/admin/manage-tourist',
    WEATHER_FORECAST: '/weather-forecast',
    ADMIN_WEATHER_FORECAST: '/admin/weather-forecast',
    ADMIN_SCHEDULE: '/admin/schedule/:tour_id',
    ADMIN_ADD_NEW_VOUCHER: '/admin/add-new-voucher',
    ADMIN_MANAGE_VOUCHER: '/admin/manage-voucher',
    ADMIN_MANAGE_CUSTOM_TOURS: '/admin/manage-custom-tours',
    TOURGUIDE_HOMEPAGE: '/tour-guide/home',
    TOURGUIDE_MISSION: '/tour-guide/missions',
};

export default routeConstants;
